name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['frontend', 'backend']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.x,
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies,
        run: |
          cd ${{matrix.project}}
          npm ci

      - name: Run Lint
        run: |
          cd ${{matrix.project}}
          npm run lint

      - name: Build Project
        if: matrix.project == 'backend'
        run: |
          cd backend
          npm run build
